### ISSUE TITLE
Before the release, change the package, groupName and credits

### ISSUE THREAD

**Issue by VmickaelV** [resourcepool/dashboard#71]
Change to Resourcepool/dashboard

* [x] Back
* [x] Android tv
* [ ] Android admin
* [x] Front

**Comment by loicortola** [comment]
Agree.
io.resourcepool everywhere?

**Comment by VmickaelV** [comment]
Yes, instead of les shoofleurs or anything

io.resourcepool.dashboard

**Comment by loicortola** [comment]
Done
