### ISSUE TITLE
As admin, we can choose which bundle to display

### ISSUE THREAD

**Issue by VmickaelV** [resourcepool/dashboard#73]

**Comment by loicortola** [comment]
What would you think about implementing a "Feed" primitive?

A Feed is basically a set of bundles.

For instance, I could have the 
**JawgOpenSpace Feed**: displaying the eBizComm + Jawg-Stats + Release-Agenda bundles
**BreakRoom Feed**: displaying the eBizComm + internal marketing content + latest news bundles
**Trainee Feed**: displaying the eBizComm + Code-Review-Agenda bundles

Then, each android app may choose which feed they want to display (only one feed allowed).

What do you think?

**Comment by loicortola** [comment]
Implemented in latest dev version for back & front
